// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 前端图标映射用的应用分类。
 */
export type AppIcon = "generic" | "web" | "java" | "python" | "database" | "server" | "container" | "terminal" | "system" | "service";
