// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 前端可识别的错误码，与 `prd/impl/implementation.md` 5.3 节一致。
 */
export type ErrorCode = "INVALID_PORT" | "INVALID_PID" | "PROCESS_NOT_FOUND" | "PROCESS_CHANGED" | "PROTECTED_PROCESS" | "CRITICAL_CONFIRM_REQUIRED" | "ACCESS_DENIED" | "UAC_CANCELLED" | "SYSTEM_API_FAILED" | "INTERNAL";
