// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketState } from "./SocketState";

export type HiddenState = { state: SocketState, count: number, };
