// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 占用者类型，决定前端的提示与可执行操作。
 */
export type OccupantKind = "normal" | "service" | "forwarder" | "critical" | "system" | "idle" | "self";
