// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiddenState } from "./HiddenState";
import type { PortBindings } from "./PortBindings";
import type { ProcessDetail } from "./ProcessDetail";

export type PidQueryResult = { process: ProcessDetail, tcp: Array<PortBindings>, udp: Array<PortBindings>, hidden: Array<HiddenState>, elapsedMs: number, };
