// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiddenState } from "./HiddenState";
import type { ProcessGroup } from "./ProcessGroup";

export type PortQueryResult = { port: number, groups: Array<ProcessGroup>, hidden: Array<HiddenState>, elapsedMs: number, };
