// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketBinding } from "./SocketBinding";

export type PortBindings = { port: number, bindings: Array<SocketBinding>, };
