// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessDetail } from "./ProcessDetail";
import type { SocketBinding } from "./SocketBinding";

export type ProcessGroup = { 
/**
 * 直接携带详情（命令行、工作目录、父进程链），前端不再单独请求详情
 */
process: ProcessDetail, bindings: Array<SocketBinding>, };
