// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppIcon } from "./AppIcon";
import type { OccupantKind } from "./OccupantKind";

export type ProcessSummary = { pid: number, name: string, appName: string, appIcon: AppIcon, exePath: string | null, 
/**
 * 进程创建时间（Unix 毫秒），用于操作前校验 PID 未被复用
 */
startTime: number | null, kind: OccupantKind, services: Array<string>, actionable: boolean, blockedReason: string | null, };
