// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamily } from "./AddressFamily";
import type { Protocol } from "./Protocol";
import type { SocketState } from "./SocketState";

export type SocketBinding = { protocol: Protocol, family: AddressFamily, localAddress: string, localPort: number, remoteAddress: string | null, remotePort: number | null, 
/**
 * UDP 没有状态
 */
state: SocketState | null, pid: number, };
